import { MessageInterface } from "@/model/Message";

// Standard API response format
export interface ApiResponse {
  success: boolean;
  message: string;
  data?: {
    isAcceptingMessages?: boolean;
    messages?: Array<MessageInterface>;
    text?: string; // The response generated by the workers ai model
    shouldReset?: boolean; // If the form should reset after submission
  };
}
